apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brawl-draft-collector-data
  namespace: brawl-draft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
