apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: refinery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MikaelSiidorow/infra.git
    targetRevision: main
    path: k8s/refinery
  destination:
    server: https://kubernetes.default.svc
    namespace: refinery
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: refinery-app
      namespace: refinery
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.name == "app").image'
    - group: apps
      kind: Deployment
      name: refinery-zero
      namespace: refinery
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.name == "zero").image'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
