apiVersion: v1
kind: Service
metadata:
  name: refinery-db
  namespace: refinery
spec:
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: refinery-db
  namespace: refinery
  labels:
    kubernetes.io/service-name: refinery-db
addressType: IPv4
ports:
  - port: 5432
endpoints:
  - addresses:
      - 10.42.0.1 # Host via K3s CNI bridge
