apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero-replica-data
  namespace: refinery
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
